"use client";
import { useState } from "react";
import UploadForm from "@/components/UploadForm"; // Keep your generator logic
import { UserCircle } from "lucide-react";
import FeedbackModal from "@/components/FeedbackModel";

export default function Dashboard() {
  const [user] = useState({ name: "User" }); // Replace with session user later

  return (
    <>
      <main className="min-h-screen bg-gray-50">
      {/* 🔝 Header */}
      <header className="bg-white border-b border-gray-200 shadow-sm">
        <div className="max-w-7xl mx-auto flex justify-between items-center px-6 py-4">
          <h1 className="text-xl font-bold text-gray-900">Fasdeem Dashboard</h1>
          <div className="flex items-center gap-3">
            <span className="text-sm text-gray-600">Hi, {user.name}</span>
            <UserCircle size={32} className="text-gray-400" />
          </div>
        </div>
      </header>

      {/* 📦 Main Content */}
      <div className="max-w-6xl mx-auto px-4 py-10 space-y-10">
        {/* Welcome Banner */}
        <div className="bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-2xl shadow-lg p-6 flex justify-between items-center">
          <div>
            <h2 className="text-2xl font-bold">Welcome back, {user.name} 👋</h2>
            <p className="text-sm text-purple-100 mt-1">
              Ready to generate high-converting product descriptions?
            </p>
          </div>
          <img src="/illustration-ai.webp" alt="AI Illustration" className="h-20 hidden sm:block" />
        </div>

        {/* Upload Generator */}
        <div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-200">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">⚡ Generate Product Descriptions</h3>
          <UploadForm /> {/* Your existing generator form */}
        </div>

        {/* History Section */}
        <div>
          <h3 className="text-lg font-semibold text-gray-900 mb-4">🕘 Recent Generations</h3>
          <div className="grid gap-4 sm:grid-cols-2">
            {[1, 2, 3].map((_, i) => (
              <div key={i} className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm hover:shadow-md transition">
                <h4 className="font-semibold text-gray-800">Sample Product {i+1}</h4>
                <p className="text-gray-600 text-sm mt-1 line-clamp-2">
                  This is an example description generated by Fasdeem AI. Real entries will appear here.
                </p>
                <button className="mt-3 text-purple-600 text-sm font-medium hover:underline">
                  Copy to Clipboard
                </button>
              </div>
            ))}
          </div>
        </div>
      </div>
    </main>
    <FeedbackModal />
    </>
  );
}
